version: '3'

services:

  gateway:
    build: ./gateway

    ports:
      - "80:80"

    depends_on:
      - app1
      - app2

  app1:
    build: ./server

    depends_on:
      - mongo
      - redis

  app2:
    build: ./server

    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo

  redis:
    image: redis