name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  test:

    runs-on:
    ubuntu-latest

    steps:

      - name: Checkout

        uses:
        actions/checkout@v4

      - name: Setup Node

        uses:
        actions/setup-node@v4

        with:
          node-version: 20

      - name: Install Backend

        run: |
          cd server
          npm install

      - name: Run Backend Tests

        run: |
          cd server
          npm test

      - name: Install Frontend

        run: |
          cd client
          npm install

      - name: Run Frontend Tests

        run: |
          cd client
          npm test